// Run with: npx tsx scripts/generate-packet-sizes-migration.ts
// Reads the JSON seed and emits a Supabase migration SQL file.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const seedPath = resolve(__dirname, '../supabase/seed_data/packet_sizes_uk.json')
const outPath = resolve(__dirname, '../supabase/migrations/00017_packet_sizes_seed.sql')

type Row = {
  ingredient_name: string
  pack_quantity: number
  pack_unit: string
  locale: string
  is_default: boolean
  notes?: string | null
}

const rows = JSON.parse(readFileSync(seedPath, 'utf8')) as Row[]

const esc = (s: string) => s.replace(/'/g, "''")

const values = rows
  .map(
    (r) =>
      `  ('${esc(r.ingredient_name)}', ${r.pack_quantity}, '${esc(r.pack_unit)}', '${esc(r.locale)}', ${r.is_default}, ${r.notes ? `'${esc(r.notes)}'` : 'null'})`,
  )
  .join(',\n')

const sql = `-- 00017_packet_sizes_seed.sql
-- AUTOGENERATED from supabase/seed_data/packet_sizes_uk.json.
-- Regenerate with: npx tsx scripts/generate-packet-sizes-migration.ts

insert into public.packet_sizes
  (ingredient_name, pack_quantity, pack_unit, locale, is_default, notes)
values
${values}
on conflict do nothing;
`

writeFileSync(outPath, sql)
console.log(`Wrote ${rows.length} rows to ${outPath}`)
